### ISSUE TITLE
Parents, children swapped on backward view

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [joshsh/brain-mode#16]

**Comment by joshsh** [comment]
Steps to reproduce?

**Comment by JeffreyBenjaminBrown** [comment]
To reproduce, just look at the backward view. The parent column shows the number of children, and vice-versa.

**Comment by joshsh** [comment]
Not a bug.  The columns show you a count of atoms above and below the reference atom *in the view*.  Forward and backward views arrange atoms in opposite directions, so the counts are opposite.

**Comment by JeffreyBenjaminBrown** [comment]
Fair enough -- I can deal with it -- but I'll bet it's going to confuse users. It's like the distinction between procedural and functional programming: It is simpler to be able to say what the column *is* than to have to understand the procedure that results in its display.

**Comment by joshsh** [comment]
Keep in mind that the goal is to generalize views; right now, we have only two view styles, or queries, which correspond very neatly to the directed parent-child relationship between notes.  This won't always be the case.  Think of the columns as an "inlinks" and an "outlinks" count, where links are abstract paths.  In some cases, it will not even be possible to define an inlinks count.

**Comment by JeffreyBenjaminBrown** [comment]
So what are inlinks and outlinks? Is it a concept I should explain in the intro vids?

**Comment by joshsh** [comment]
I mean the inbound and outbound links to or from a node in a directed graph.  The meta columns show the in-degree and the out-degree of each node with respect to some relationship, be it parent->child, child->parent, sibling->sibling, or something else.  Those edges don't actually exist in the graph database; they're derived from structures that do exist in the database, and these are even a little further removed from simple parents and children in the new data model. 

Would write/code more, but a migraine is kicking my butt tonight, or rather my head.
