### ISSUE TITLE
master branch: brain-mode not connecting to server

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [joshsh/brain-mode#21]
There are now two branches on dockerhub: [smsn](https://hub.docker.com/r/jeffreybbrown/smsn/) and [smsn-develop](https://hub.docker.com/r/jeffreybbrown/smsn-develop/). I've updated the DockerHub documentation, and moved all the old smsn images to smsn-develop. The smsn wiki still doesn't mention the develop branch.

Contrary to their intended uses, though, I could not get the master branch to work. I think maybe smsn-mode:master is out of sync with smsn:master. I changed `require smsn-mode` to `require brain-mode` in my .emacs file, upon which Emacs seemed satisfied, but when I tried to connect to the graph by searching for some text, it just cycled forever (by which I mean maybe thirty seconds each time I tried before reissuing the command a few times).

**Comment by joshsh** [comment]
Is this still an issue (post- 1.4 release)?

**Comment by JeffreyBenjaminBrown** [comment]
Nope!
