### ISSUE TITLE
Visit in wikipedia not working

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [joshsh/brain-mode#22]
When I enter `C-c C-t C-b w`, after the `b` and before the `w`, I get the error `C-c C-t C-b is undefined` -- and yet I can see the definition of that shortcut in smsn-commands.el.

**Comment by joshsh** [comment]
How do you see that shortcut in smsn-commands.el?  You shouldn't (in develop, anyway).  I decided that these browser shortcuts were too specific to my own needs, and moved them to the [example init file](https://github.com/synchrony/smsn-mode/blob/develop/doc/emacs-init-example.el).

**Comment by JeffreyBenjaminBrown** [comment]
Wrong branch was the problem. Thanks!
