### ISSUE TITLE
Is develop safe to merge into master right now?

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [joshsh/brain-mode#28]
I just fast-forwarded my smsn-mode repo by 3 years by switching from master to develop. The 2 commits that happened in those three years were one to fix the set-source command (that's what prompted me to update) and another labeled "Add YAML read/write commands". It seems like none of that should be incompatible with the rest of the master branch, right? I suspect merging would be good because as it standsd set-source in master is broken.

**Comment by joshsh** [comment]
Yes, we could probably just pull develop into master at this point. Anyone
using SmSn will be building it from source or starting up your Docker
container, not including it in their Maven or Gradle or whatever.

**Comment by JeffreyBenjaminBrown** [comment]
Roger, done, thanks!
